fragment TextContentComponent on TextContent {
  id
  type
  denomination
  is_published
  is_required
  content
  component_id
  progress {
    id
    content_component_id
    is_completed
  }
}

fragment VideoContentComponent on VideoContent {
  id
  type
  denomination
  is_published
  is_required
  url
  component_id
  progress {
    id
    content_component_id
    is_completed
  }
}

fragment YouTubeContentComponent on YouTubeContent {
  id
  type
  denomination
  is_published
  is_required
  youtube_video_id
  description
  component_id
  progress {
    id
    content_component_id
    is_completed
  }
}
