fragment HomeCourse on Course {
  id
  denomination
  slug
  level
  image
  rating
  participationCount
  status
  progress {
    completedComponents
    totalComponents
    progressPercentage
    isCompleted
  }
  instructor {
    id
    first_name
    last_name
    avatar_url
  }
}

fragment Statistics on Statistics {
  enrolledCoursesCount
  completedCoursesCount
}

fragment HomeTeacher on Teacher {
  id
  first_name
  last_name
  avatar_url
}

query Home {
  enrolledCourses {
    ...HomeCourse
  }
  completedCourses {
    ...HomeCourse
  }
  followingFeedByTeachers(teachersFirst: 3, maxTeachers: 3) {
    totalCount
    teacher {
      ...HomeTeacher
    }
    items {
      ... on Course {
        ...CatalogCourse
      }
      ... on Program {
        ...CatalogProgram
      }
    }
  }
  me {
    id
    statistics {
      ...Statistics
    }
  }
}
