export const ACCESS_DENIED = 'ACCESS_DENIED';
export const PERMISSION_DENIED = 'PERMISSION_DENIED';
export const MUST_ENROLL_TO_COURSE_FIRST = 'MUST_ENROLL_TO_COURSE_FIRST';

export const SIGN_UP_FIRST = 'SIGN_UP_FIRST';
